stages:
  - release
  - deploy

build and push to registry:
  stage: release
  image: gitlab/dind:latest
  only:
    - master
  before_script:
    - docker version
    - "docker info"
    - "docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY"
  script:
    - "docker build -t $CI_REGISTRY/vnappmob/vapi:latest ."
    - "docker push $CI_REGISTRY/vnappmob/vapi:latest"
  after_script:
    - "docker logout $CI_REGISTRY"

deploy to production:
  stage: deploy
  image: gitlab/dind:latest
  services:
    - docker:dind
  only:
    - master
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - rsync -r ./docker-compose.yml root@$DEPLOY_SERVER_IP:~/vapi/
    - ssh root@$DEPLOY_SERVER_IP "docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY; cd vapi; docker pull $CI_REGISTRY/vnappmob/vapi:latest; docker-compose stop; SECRET_KEY=$DEPLOY_SECRET_KEY VPRICE_FCM_KEY=$VPRICE_FCM_KEY DB_HOST=$DB_HOST DB_USER=$DB_USER DB_PASSWORD=$DB_PASSWORD docker-compose up -d"
