"""app/api/exchange_rate/vcb.py"""
import requests
from flask import Blueprint, request, make_response, jsonify, current_app  # pylint: disable=W
from app.db.db_connect import VDBConnect, MySQLdb
from app.errors import error_response
from app.api.exchange_rate import bp


@bp.route('/api/exchange_rate/vcb', methods=['GET'])
def api_exchange_rate_vcb_get():
    """.. :quickref: 01. VCB; Get all VCB exchange rate

    This function allows users to get the latest VCB exchange rate

    **Request**:

    .. sourcecode:: http

      GET /api/exchange_rate/vcb HTTP/1.1
      Host: https://vapi.vnappmob.com
      Accept: application/json

    **Response**:

    .. sourcecode:: http

      HTTP/1.1 200 OK
      Vary: Accept
      Content-Type: application/json

      {
          "results": [
              {

              }
          ]
      }

    :query api_key: API Key generated by VNAppMob
    :resheader Content-Type: application/json
    :status 200: results
    """
    db_connect = VDBConnect()
    if db_connect.connected:
        try:
            request_api = request.args.get('api_key', default='', type=str)

            slash_settings = db_connect.get_slash_setting()
            if slash_settings['api'] == request_api:
                statements = (
                    'SELECT t1.currency, t1.buy_cash, t1.buy_transfer, t1.sell '
                    'FROM vnappmob_exchange_rate_vcb  t1 '
                    'GROUP BY currency '
                    'ORDER by t1.currency, t1.datetime')
                try:
                    results = db_connect.readall(statements)
                    return make_response((jsonify({'results': results})), 200)
                except MySQLdb.Error as err:  # pylint: disable=E
                    return error_response(400, str(err))
            return error_response(403, 'Invalid api_key')
        finally:
            db_connect.close()
    return error_response(404, str(db_connect.error))


@bp.route('/api/exchange_rate/vcb', methods=['POST'])
def api_exchange_rate_vcb_post():
    """.. :quickref: 01. VCB; Post new exchange rate

    Limited function that allows data manager to push newest price

    **Request**:

    .. sourcecode:: http

      POST /api/exchange_rate/vcb HTTP/1.1
      Host: https://vapi.vnappmob.com
      Accept: application/json

    **Response**:

    .. sourcecode:: http

      HTTP/1.1 201 Created
      Vary: Accept

    :resheader Authorization: API Key generated by VNAppMob
    :resheader Content-Type: application/json
    :<json string currency: currency code (3 chars: VND, USD...)
    :<json float buy_cash: buy_cash
    :<json float buy_transfer: buy_transfer
    :<json float sell: sell
    :status 201: Successful update data
    :status 403: Invalid api_key
    :status 400: Error
    """
    db_connect = VDBConnect()
    if db_connect.connected:
        try:
            request_api = request.headers['Authorization']
            slash_settings = db_connect.get_slash_setting()
            if slash_settings['api'] == request_api:
                json_data = request.get_json()

                last_row = db_connect.readone(
                    "SELECT * FROM vnappmob_exchange_rate_vcb "
                    "WHERE currency = " + json_data['currency'] + " "
                    "ORDER BY id DESC LIMIT 1;")
                if any([
                        float(last_row['buy_cash']) != float(
                            json_data['buy_cash']),
                        float(last_row['buy_transfer']) != float(
                            json_data['buy_transfer']),
                        float(last_row['sell']) != float(json_data['sell']),
                ]):
                    vals = []
                    statements = (
                        "INSERT INTO vnappmob_exchange_rate_vcb "
                        "(id, currency, buy_cash, buy_transfer, sell) "
                        "VALUES (NULL, %s, %s, %s, %s);")
                    vals.extend((json_data['currency'], json_data['buy_cash'],
                                 json_data['buy_transfer'], json_data['sell']))
                    db_connect.writecommit(statements, tuple(vals))

                    headers = {
                        'Authorization':
                        'key=' + current_app.config['VPRICE_FCM_KEY'],
                        'Content-Type':
                        'application/json'
                    }

                    push_data_currency = json_data['currency']
                    push_data_buy_cash = '{:,d}'.format(
                        int(json_data['buy_cash']))
                    push_data_buy_transfer = '{:,d}'.format(
                        int(json_data['buy_transfer']))
                    push_data_sell = '{:,d}'.format(int(json_data['sell']))
                    data = (
                        '{"notification": {"title": "vPrice - Biến động giá VCB-%s,'
                        '"body": "Mua tiền mặt: %s'
                        '\nMua chuyển khoản: %s'
                        '\nBán: %s","sound": "default"},"priority": "high",'
                        '"data": {"click_action": "FLUTTER_NOTIFICATION_CLICK",'
                        '"id": "/topics/exchange_rate/vcb","status": "done"},'
                        '"to": "/topics/exchange_rate/vcb"}' %
                        (push_data_currency, push_data_buy_cash,
                         push_data_buy_transfer, push_data_sell))

                    response = requests.post(
                        'https://fcm.googleapis.com/fcm/send',
                        headers=headers,
                        data=data.encode('utf-8'))
                    print(response.status_code, response.text)

                    return make_response((jsonify({'results': 201})), 201)
                return make_response((jsonify({'results': 200})), 200)
            return error_response(403, 'Invalid api_key')
        except MySQLdb.Error as err:  # pylint: disable=E
            return error_response(400, str(err))
        finally:
            db_connect.close()
    return error_response(404, str(db_connect.error))
